[tool.poetry]
name = "affinis"
version = "0.1.0"
description = ""
authors = ["tbsexton <thurston.sexton@nist.gov>"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.1.3"
networkx = "^2.5"
anndata = "^0.8.0"
scikit-learn = "^1.2.0"
static-frame = "^1.0.0"
geomstats = "^2.5.0"

[tool.poetry.group.dev.dependencies]
pytest = "^5.2"
ipykernel = "^6.9.2"
seaborn = "^0.12.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
